language: python
sudo: false
matrix:
  include:
    - python: 3.6
      env: TOXENV=py3flake8
    - python: 3.6
      env: TOXENV=doc
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.6
      env: TOXENV=py36

install:
  - travis_retry pip install tox

script:
  - tox
